// TrackerScriptEditorWindowDefs.h
// Generated by Interface Elements (Window v2.0) on Apr 25 1998
// Do not modify this file!



/*

Views in TrackerScript editor window:
	"bg bview"  (BView)
	"command box"  (BBox)
	"command"  (BTextView)
	"script box"  (BBox)
	<unnamed> (BTextView)

*/


