// TrackerScriptEditorWindow.h
// Generated by Interface Elements (Window v2.0) on Apr 25 1998
// This is a user written class and will not be overwritten.

#ifndef _TRACKERSCRIPTEDITORWINDOW_H_
#define _TRACKERSCRIPTEDITORWINDOW_H_

#include <Window.h>
#include <Entry.h>
#include <TextView.h>
#include <CheckBox.h>


class TrackerScriptEditorWindow : public BWindow
{
	entry_ref entry;
	
public:
	TrackerScriptEditorWindow(const entry_ref *);
	~TrackerScriptEditorWindow(void);
	
	void Load();
	void Save();
	
	virtual bool QuitRequested();
	virtual void MessageReceived(BMessage *);
	
private:
		BTextView* fTextView;
		BCheckBox* fRunTerminal;
};

#endif
